language: python
python:
    - "3.5"

os:
    - linux


install:
  - pip install --upgrade pip
  - pip install cython
  - travis_wait pip install -r requirements.txt
  - pip install pytest-cov
  - python setup.py install
  - pip install coveralls 

script: 
    - py.test -v --cov=arspy

after_success:
    - coveralls
