// This is an autogenerated header file
#ifndef JULIA_VERSION_H
#define JULIA_VERSION_H
#define JULIA_VERSION_STRING "0.4.7"
#define JULIA_VERSION_MAJOR 0
#define JULIA_VERSION_MINOR 4
#define JULIA_VERSION_PATCH 7
#define JULIA_VERSION_IS_RELEASE 1
#endif
